// <auto-generated />
using System;
using Core3_Framework.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Core3_Framework.Data.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20190818225852_IResDbInit")]
    partial class IResDbInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "3.0.0-preview7.19362.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Core3_Framework.Contracts.DataContracts.AuditTables", b =>
                {
                    b.Property<string>("TableName")
                        .HasMaxLength(255);

                    b.HasKey("TableName");

                    b.ToTable("AuditTable");
                });

            modelBuilder.Entity("Core3_Framework.Contracts.DataContracts.Audits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<string>("AdditionalValue");

                    b.Property<string>("KeyValues")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NewValues");

                    b.Property<string>("OldValues");

                    b.Property<string>("ProcessOwner")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("ProcessTime")
                        .HasColumnType("timestamp");

                    b.Property<string>("ProcessType")
                        .IsRequired()
                        .HasMaxLength(6);

                    b.Property<Guid?>("RelationId");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Audit");
                });

            modelBuilder.Entity("Core3_Framework.Contracts.DataContracts.CacheItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("CacheItem");
                });

            modelBuilder.Entity("Core3_Framework.Contracts.DataContracts.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<string>("CategoryName")
                        .HasMaxLength(100);

                    b.Property<string>("SeoURL")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Core3_Framework.Contracts.DataContracts.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<int?>("CategoriesId");

                    b.Property<int>("CategoryId");

                    b.Property<string>("ProductName")
                        .HasMaxLength(100);

                    b.Property<int>("QuantityPerUnit");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal");

                    b.Property<int>("UnitsInStock");

                    b.HasKey("Id");

                    b.HasIndex("CategoriesId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Core3_Framework.Contracts.DataContracts.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int?>("UsersId");

                    b.HasKey("Id");

                    b.HasIndex("UsersId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Core3_Framework.Contracts.DataContracts.UserRoles", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnName("User_Id");

                    b.Property<int>("RoleId")
                        .HasColumnName("Role_Id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasName("IX_Role_Id");

                    b.HasIndex("UserId")
                        .HasName("IX_User_Id");

                    b.ToTable("User_Role");
                });

            modelBuilder.Entity("Core3_Framework.Contracts.DataContracts.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<string>("FullName")
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .HasMaxLength(20);

                    b.Property<string>("Username")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Core3_Framework.Contracts.DataContracts.Products", b =>
                {
                    b.HasOne("Core3_Framework.Contracts.DataContracts.Categories", "Categories")
                        .WithMany("Products")
                        .HasForeignKey("CategoriesId");
                });

            modelBuilder.Entity("Core3_Framework.Contracts.DataContracts.Roles", b =>
                {
                    b.HasOne("Core3_Framework.Contracts.DataContracts.Users", null)
                        .WithMany("Roles")
                        .HasForeignKey("UsersId");
                });

            modelBuilder.Entity("Core3_Framework.Contracts.DataContracts.UserRoles", b =>
                {
                    b.HasOne("Core3_Framework.Contracts.DataContracts.Roles", "Roles")
                        .WithMany("UserRole")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_dbo.User_Role_dbo.Role_Role_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core3_Framework.Contracts.DataContracts.Users", "Users")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_dbo.User_Role_dbo.User_User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
